services:
  dynamodb:
    container_name: tubebuddy-dynamodb
    image: amazon/dynamodb-local
    expose:
      - "8000"
  app:
    container_name: tubebuddy-app
    build: .
    environment:
      AWS_ACCESS_KEY_ID: 'aaa'
      AWS_SECRET_ACCESS_KEY: 'bbb'
    volumes:
      - ./app:/code/app
    ports:
      - 80:80
    depends_on:
      - dynamodb
